repos:
  - repo: https://github.com/henryiii/conda-clang-format
    rev: v12.0.1
    hooks:
      - id: clang-format
        args: [--style=Google]
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    - id: cmake-format
